Chapter 3
ro-msg-spring-training/online-shop-hilbert-erwin pull request #3
Opened 2021-04-08 12:07 UTC by hilbert-erwin

2021-04-08 15:10 UTC, cristinacalbaza requested changes

2021-04-08 15:10 UTC, cristinacalbaza commented on src/main/java/ro/msg/learning/shop/entity/Location.java
> +    private String address_street_address;
You can create a separate Entity named Address with these fields. In this way you remove duplicates because the fields are used also in Order entity.

2021-04-08 15:10 UTC, cristinacalbaza commented on src/main/java/ro/msg/learning/shop/entity/Order.java
> +    private String address_street_address;
Use here the new entity "Address" mentioned before.

2021-04-08 15:10 UTC, cristinacalbaza commented on src/main/java/ro/msg/learning/shop/entity/Revenue.java
> +    private String name;
Do you need the name here?

2021-04-09 06:28 UTC, hilbert-erwin commented
fixed everything

2021-04-15 06:01 UTC, merged